netconfdriver/service/common.py
netconfdriver/service/configuration/__init__.py
netconfdriver/service/jinja_conversion.py
netconfdriver/service/location/deployment_location.py
netconfdriver/service/operations/config_operations.py
netconfdriver/service/resourcedriver.py
tests/unit/netconf/template/Create.xml
tests/unit/netconf/template/Update.xml
tests/unit/test_example.py

handle structured data , private key

---

netconfdriver/pkg_info.json

#18 
Update develop branch version to 0.1.0.dev0
Signed-off-by: Haynes Davis <Haynes.Davis@ibm.com>

Update develop branch version

---

docker/Dockerfile
setup.py

Issue 20 - Fixing Vulnerabilities

---

CONTRIBUTING.md
README.md
docs/Onboarding.md
docs/index.md

#24 
Update documentation on onboarding
Signed-off-by: Haynes Davis <Haynes.Davis@ibm.com>

Update documentation on onboarding

---

CHANGELOG.md

changelog_v0.1.0 
Signed-off-by: haynesdavis <haynesdavis@gmail.com>

changelog_v0.1.0

---

netconfdriver/pkg_info.json

Issue 29 - Updating ignition version to 3.4.1

---

CHANGELOG.md

Merge Develop -> Master branch for release candidate

Merge Develop -> Master branch for release candidate 

---

netconfdriver/pkg_info.json

Merge master to develop for Release 0.1.2

Merge master to develop for Release 0.1.2

---

netconfdriver/pkg_info.json

Revert "Update pkg_info.json"

---

netconfdriver/pkg_info.json

Post release cleanup

---

CHANGELOG.md

merge develop-> master to release 0.1.4-rc1

merge develop-> master to release 0.1.4-rc1

---

netconfdriver/service/operations/config_operations.py
netconfdriver/service/resourcedriver.py

removed sensitive info from logger

---

netconfdriver/pkg_info.json

Update Ignition version to latest 3.5.1

---

CHANGELOG.md

updated CHANGELOG for release 0.2.0

update CHANGELOG for release 0.2.0

---

CHANGELOG.md
netconfdriver/pkg_info.json
netconfdriver/service/operations/config_operations.py
netconfdriver/service/resourcedriver.py

Merged Develop to Master for release 0.2.0

Merge Develop to Master for release 0.2.0

---

build.py

Build the netconf-driver with 'rc' tag

---

CHANGELOG.md
build.py

merge develop -> master branch for release 0.2.1

merge develop -> master branch for release 0.2.1

---

netconfdriver/pkg_info.json

Cleanup activity for release 0.2.1-rc1

Cleanup activity for release 0.2.1-rc1

---

netconfdriver/pkg_info.json

Update Ignition with latest version 3.5.2

---

CHANGELOG.md

Updated CHANGELOG.md for release v0.2.1-rc2

Update CHANGELOG.md for release v0.2.1-rc2

---

CHANGELOG.md

merge develop->master for release 0.2.1-rc2

merge develop->master for release 0.2.1-rc2

---

netconfdriver/pkg_info.json

Cleanup activity for release v0.2.1-rc2

Cleanup activity for release v0.2.1-rc2

---

CHANGELOG.md

merge develop->master to release v0.2.1

merge develop->master to release v0.2.1

---

README.md
netconfdriver/service/common.py
netconfdriver/service/jinja_conversion.py
netconfdriver/service/location/deployment_location.py
netconfdriver/service/operations/config_operations.py
netconfdriver/service/resourcedriver.py

added flexibility to update candidate or running datastore of netconf server

---

CHANGELOG.md
README.md
netconfdriver/service/common.py
netconfdriver/service/jinja_conversion.py
netconfdriver/service/location/deployment_location.py
netconfdriver/service/operations/config_operations.py
netconfdriver/service/resourcedriver.py

merge develop->master for release v0.3.0

merge develop->master for release v0.3.0

---

netconfdriver/pkg_info.json

cleanup activity for release v0.3.0

cleanup activity for release v0.3.0

---

CHANGELOG.md

Merge develop->main branch for release 0.3.2

Merge develop->main branch for release 0.3.2

---

setup.py

Security Vulnerability [paramiko]

---

docker/Dockerfile
netconfdriver/pkg_info.json
setup.py

changes required for ignition 3.6.0 to fix [werkzeug] vulnerability

---

setup.py

upgraded gunicorn to 22.0.0 to fix  CVE-2024-1135

---

netconfdriver/pkg_info.json

Updated Ignition and driver version in pkg_info.json  

---

netconfdriver/service/resourcedriver.py

added if statement before unlink rsa_key_path 
fixes Issue #99

added if before unlink  rsa_key_path to fix #99

---

netconfdriver/service/resourcedriver.py

Reverts IBM/netconf-driver#100

Revert "added if before unlink  rsa_key_path to fix #99"
